apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

patches:
  - path: service.deployment.patch.yaml
    target:
      kind: Deployment
      name: service
  - path: bff.deployment.patch.yaml
    target:
      kind: Deployment
      name: bff
  - path: spa.deployment.patch.yaml
    target:
      kind: Deployment
      name: spa
